### ISSUE TITLE
Version 2.0.11 is missing font size and color option

### ISSUE THREAD

**Issue by gino2014** [magefan/module-wysiwyg-advanced#19]
Dear support,

thanks for this helpfull extensions. We are happy with it and using it now a long time. But after upgrading to current version 2.0.11 the font size and color option are missing. After switching back to 2.0.10 the are available again.
![Missing](https://user-images.githubusercontent.com/6517231/162563094-270fa187-51a3-452b-ac02-8b40eb82772f.JPG)

Maybe you could take a look into it.
Thanks in advance
Gino

**Comment by magefan** [comment]
@gino2014 , think it was broken during this pr https://github.com/magefan/module-wysiwyg-advanced/commit/23d1aa5ff8e7781b0fb10c808f775652c0b48bfe .

The issue is now fixed by this commit https://github.com/magefan/module-wysiwyg-advanced/commit/7ae487a598fed3cb49d4702275b03181191f7500

Please confirm that this fix the issue for you.

**Comment by gino2014** [comment]
@magefan , 
thanks for helping. We updatdet to 2.0.11 again. Now we are able to set the color option again. But the font size is still missing.

![Version2 0 11after fix](https://user-images.githubusercontent.com/6517231/164191087-b6034496-5ca3-48c2-becf-ecfb17334c47.JPG)

Kind Regards
Gino

**Comment by magefan** [comment]
@gino2014 , please update to v2.0.12, just released - it has the fix.

**Comment by gino2014** [comment]
@magefan , thanks for your fast help and providing such useful extension. 
Kind Regards Gino
